dist: xenial
sudo: required
language: java
services:
  - docker
  - mongodb
  - mysql
  - postgresql

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "fTjOKaUUUKOSV32XrSLxkT7rV0pJe9IqCam8Oxfs4UB0ykfGWLiCvtvAsbZT8JUr8/EYyH4k/NGus73pn92gM7xkpg4yMuuIMMvDGN7/YpI3Q
PcxhmO+/h9JMqSZZniFuMVtOJsf/YIISmFIKRN82/3tlk9j53PCltOVD+x3T7g3W1jYwlCxpYfsJgBS0Svlwdq2Nawosb/UaSmWe8mpIgpOyu6Z30XTWpVvT
E82gMQvGGpB6yGoS5sACLozenVS+DJlGSvIvzXpZVcqkpf+NJGGadDPX0Cii3hIetirjha3/bDekGOZxbOS/8lCq3R9q3gcdcn3JLqBV9f8FS/5L8A8zz872
Q1/P0w7NEHjP+EsOs/hg/dMRAC7WxoRCY/v8lEOK+ady9Zkz14blqxEAN+YmuMwhakojmoXZYzmFbBL5IMKsJkvM4MRCWP95Om45Z5J8YN264g/3fn7T6H1k
Atyrchr3PhqWwwETaKWcMDTrywRl9KDaL3sXQNpf+u4M6HkMRWciYoMd06sLrZwXhVdT0NYXXVbRT8ieWSXHIOaEnAR94Hcs/pDofv9Ogi0HObxNic9FvFwD
2mTVRW0bORg2EFAvb0oNQBZUV3NKGqeTEHv4PbBb1idlLU1hweNyncjnGppKPSuv36EJb9n/dGoFQTbluByXjkgJ/g/iX4="
    - DOCKER_USERNAME=phelger
    - secure: "O6MzNHzpMaOcp4Rnwie7mSX27dLs9kdkfH/1QIPmu+XpKsYGh7lmRqV/PvPJKpfMXj3nP+wo3B05pNxO62VMx9c3ZlKmkRGxxnUnQqKS6uNPcKjXfAe8DB7TsrQ27jwNya+Upr8MhIikDVQIPHxq0
KJPT8N3asYI/CpUhbXE9eeDmJow3/5qz57Y2+cA0hrcRZjIocsVqa0Mk2/MWXZ1nAA/XG4y9lnqAOKWJLyLn2nFbkEZMqv2jPcm6cZXBjqoOgse26MDt8WJ5MQO2aQkuArATgm+zbpJn9EpdUiJYymo/CwLVXX+h
7feVQFZ/L1ZyOX/lZMHPUC+iGlEdQqEcX2Dwj9+nbNbX6iXV5Wwlsx0K6Nsn2gxCcXt+S/3+pas3iSMTQpqV0iZ58RLS2naTBX7Os/RFEYd5sbQPncQ3NV68x1r+rir+BBm9UAxeOInMHLeniqkEhyvGS2tOuxT5
Q6NjWK7QYd3tCCWB6Klv1Z+vVS4m8KM07aMr9gtnvrOVJGTbMc76jpefFFmjHUnY0EC+DJI1Tj7yJhPdC2W3/N9udTW5vr/96AB4xS5P0CfjeGcegqf1Gz7PiCUFnCsY8PTpFlrDqTI8utQu8vazJoEEwe0xZnb1
ZPLWVXouSl6cpXzE412fDmZ82mPafrsAal3mUJel8a2lUco1mYi9mk="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "b2sMndZKOLgYNPwW5Wa9lr5SpRmJAXjCt6/0YQT/9prtdFOvzU9flRE9b+uSZl5tgPFuZiCP8lr8usJyd5evTr+bubaUAKAlwS4j3jHjQ9d2I8uY4ss9qcUcA/q5O6ZcRv8p3StByXdvGUtlbkWam
WIzOR2ODJaULiTiXflWnqP7WNfAHdwUdkitlfTNtgCcNKrWa6nEWDL7qFmZ7E6ro838jUMY3tiEVpr7luDYpTTXy2ztT92zYzT/PFfX/tWHVpSGU4l5AaU7b33rj4//6zEEN6vy9KeVPE3+ak8MIupvMsxLrCail
pc2onmHKAT9taBJgSTuuTq2ws6DODhp5PBJkaHk02Z3xfr8dtLYKd1fG2ZkJLTQXqeiwt11RErJQgdirlqaUD3X9medMjcFSLYp5tAgLrcmkMFE2oI7UmNBy/+0F6P4Q8ydKm6uFAMmihjR7G9UBksttOjNjlNKO
1y9W+K93OFSeXz54H/ejuqSn3z7d4W/H49guksThPzVzsVhMc8Cu9pYfArGC/UWby4OD35iyicickplsO7OoGdo5cykBGnaaSrP4Z19VPLYa8EFT994n06uAQyOz/ZQ3xLIEHE0IrIg8kTFMhYq1Yx9JTocNc+6f
vVaztY+EpsNIh9mwkO3YjW4KGS3DGKiqJ0uA/tElX0EUNoQ55re8WM="

before_install:
  - psql -c "CREATE ROLE smp LOGIN PASSWORD 'smp';" -U postgres
  - psql -c "CREATE DATABASE smp WITH ENCODING = 'UTF8' OWNER = smp;" -U postgres
  
install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
# build XML version
        - docker build --pull -t phoss-smp-snapshot-from-source-xml -f docker/Dockerfile-snapshot-from-source-xml .
        - docker tag phoss-smp-snapshot-from-source-xml phelger/phoss-smp-xml:snapshot
# build SQL version
        - docker build --pull -t phoss-smp-snapshot-from-source-sql -f docker/Dockerfile-snapshot-from-source-sql .
        - docker tag phoss-smp-snapshot-from-source-sql phelger/phoss-smp-sql:snapshot
# build MongoDB version
        - docker build --pull -t phoss-smp-snapshot-from-source-mongodb -f docker/Dockerfile-snapshot-from-source-mongodb .
        - docker tag phoss-smp-snapshot-from-source-mongodb phelger/phoss-smp-mongodb:snapshot
# push both
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push phelger/phoss-smp-xml:snapshot
        - docker push phelger/phoss-smp-sql:snapshot
        - docker push phelger/phoss-smp-mongodb:snapshot
        - docker logout
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
