version: "3"

services:
  smp1:
    image: "phelger/phoss-smp-sql:snapshot"
    expose:
      - "8080"
  smp2:
    image: "phelger/phoss-smp-sql:snapshot"
    expose:
      - "8080"
  smp3:
    image: "phelger/phoss-smp-sql:snapshot"
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - smp1
      - smp2
      - smp3
    ports:
      # SMP visible at http://localhost:9091
      - "9091:9090"
