version: "3"

services:
  smp:
    image: "phelger/phoss-smp-sql:snapshot"
    # scale: 3
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - smp
    ports:
      - "9090:9090"
